//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleBuilderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeEvent()
        {
            this.EmployeeTrades = new HashSet<EmployeeTrade>();
        }
    
        public int ID { get; set; }
        public System.DateTime ShiftStartTime { get; set; }
        public System.DateTime ShiftEndTime { get; set; }
        public decimal ShiftHours { get; set; }
        public string ThemeColor { get; set; }
        public int EmployeeID { get; set; }
        public int ScheduleID { get; set; }
        public int ApprovedStatusID { get; set; }
    
        public virtual ApprovedCode ApprovedCode { get; set; }
        public virtual User User { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeTrade> EmployeeTrades { get; set; }
    }
}
