//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleBuilderApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTrade
    {
        public int ID { get; set; }
        public string Position { get; set; }
        public int EventID { get; set; }
        public int AcceptStatusID { get; set; }
        public int ApprovedStatusID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SwapUserID { get; set; }
    
        public virtual AcceptCode AcceptCode { get; set; }
        public virtual ApprovedCode ApprovedCode { get; set; }
        public virtual EmployeeEvent EmployeeEvent { get; set; }
        public virtual User User { get; set; }
    }
}
